### ISSUE TITLE
OSQP interface update

### ISSUE THREAD

**Issue by stephane-caron** [qpsolvers/qpsolvers#323]
Following the release of OSQP 1.0 last Sunday, the following error has appeared in continuous integration:

```
        File "/home/runner/work/qpsolvers/qpsolvers/qpsolvers/solvers/osqp_.py", line 137, in osqp_solve_problem
          success_status = osqp.constant("OSQP_SOLVED")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: constant() missing 1 required positional argument: 'algebra'
```

It looks like the OSQP interface in qpsolvers will need an update to work with OSQP 1.0+.

**Comment by stephane-caron** [comment]
Closing this issue as this has been addressed by now.
